### ISSUE TITLE
[feature] Implement Interface for DB (Relational & TS)

### ISSUE THREAD

**Issue by gaocegege** [dyweb/sundial#6]

**Comment by at15** [comment]
@gaocegege why mongodb? ....

**Comment by gaocegege** [comment]
Now we support SQLite, MySQL and many other RDB with the help of gorm.io

The last thing we should do is to import the interface of TS DB and implement the interface for InfluxDB.

**Comment by at15** [comment]
I used to have library for tsdb https://github.com/libtsdb/libtsdb-go (no longer maintained) However since we are only using influxdb, its write protocol is pretty simple, for read, they have a new query language called flux https://github.com/influxdata/flux for InfluxDB 2.0

The easiest way is to check what grafana is using @xplorld https://github.com/grafana/grafana/tree/master/pkg/tsdb/influxdb (it is for 1.0)

**Comment by gaocegege** [comment]
I am not sure if we will only support influxdb. But SGTM if my leader thinks so.

**Comment by at15** [comment]
@gaocegege I think it's easier to just fix to one tsdb for now, let's have working prototype then we can think about a more general interface with more backends

**Comment by gaocegege** [comment]
SGTM

**Comment by xplorld** [comment]
what should we actually do? AFAIK we have to apppend latest heartbeat records to the DB. Is that all?

**Comment by at15** [comment]
@xplorld we still need to read aggregated result from tsdb (i.e. avg time spend on project X today), tsdb can give those results in near real time, however we can cache result in rdb since what happened yesterday won't change, see #9
